esphome:
  # ...
  libraries:
    - "SPI"
    - "Wire"
    - "Adafruit BusIO"
    - "Adafruit VCNL4040"
  
external_components:
  - source:
      type: git
      url: https://github.com/isycat/esphome_vcnl4040.git
      ref: "0.2"
    components: [vcnl4040]

vcnl4040:
  update_interval: 10s
  proximity:
    name: Proximity
  lux:
    name: Lux
  rawlight:
    name: Raw Light
